//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlykhohang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiet_nhapkho
    {
        public int id { get; set; }
        public string ma_phieu { get; set; }
        public string ma_vattu { get; set; }
        public string sl_vattu { get; set; }
        public string ghichu { get; set; }
    }
}
