//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlykhohang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quanlykhoEntities : DbContext
    {
        public quanlykhoEntities()
            : base("name=quanlykhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kho> khoes { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<vattu> vattus { get; set; }
        public virtual DbSet<nhapkho> nhapkhoes { get; set; }
        public virtual DbSet<donvitinh> donvitinhs { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<chitiet_nhapkho> chitiet_nhapkho { get; set; }
        public virtual DbSet<lophop> lophops { get; set; }
        public virtual DbSet<sinhvien> sinhviens { get; set; }
        public virtual DbSet<khoa> khoas { get; set; }
    }
}
