//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlykhohang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public int id { get; set; }
        public string ma_nv { get; set; }
        public string hoten_nv { get; set; }
        public bool gioitinh_nv { get; set; }
        public int std_nv { get; set; }
        public string diachi_nv { get; set; }
    }
}
