//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlykhohang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhapkho
    {
        public int id { get; set; }
        public string ma_phieu { get; set; }
        public System.DateTime ngay_nhap { get; set; }
        public string ma_nv { get; set; }
        public string ma_kho { get; set; }
        public string lydo { get; set; }
    }
}
