//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlykhohang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhvien
    {
        public int id { get; set; }
        public string ma_sv { get; set; }
        public string ten_sv { get; set; }
        public string diachi { get; set; }
        public string ma_lop { get; set; }
        public string ma_kh { get; set; }
    }
}
