//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlykhohang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vattu
    {
        public int id { get; set; }
        public string ma_vt { get; set; }
        public string ten_vt { get; set; }
        public string dvt_vt { get; set; }
        public int soluong_vt { get; set; }
        public string loai_vt { get; set; }
    }
}
